brew install --cask anydesk
brew install --cask brave-browser
brew install --cask discord
brew install --cask folx
brew install --cask iterm2
brew install --cask keka
brew install --cask microsoft-remote-desktop
brew install --cask notion
brew install --cask postman
brew install --cask rectangle
brew install --cask slack
brew install --cask spotify
brew install --cask vlc
brew install --cask zoom
