-- local autocmd = require("core.autocmds")

-- Formatting Code on Save
-- autocmd.BufWritePost = {
--   '*',
--   function()
--     for _, client in ipairs(vim.lsp.get_active_clients()) do
--       if client.attached_buffers[vim.api.nvim_get_current_buf()] then
--         vim.lsp.buf.format()
--         return
--       else
--         return
--       end
--     end
--   end,
-- }
