skip_global_compinit=1

# --- Exports
export ZSH=$HOME/.oh-my-zsh
export ZSH_PLUGINS=$ZSH/custom/plugins
export ZSH_SCRIPTS=$HOME/.zshscripts
export EDITOR='vim'
export ZK_NOTEBOOK_DIR=$HOME/Documents/Development/journal

ZSH_THEME="robbyrussell"

plugins=(git tmux brew colorize common-aliases zsh-interactive-cd)

ZSH_TMUX_AUTOSTART=false

source $ZSH_SCRIPTS/.aliases
source $ZSH/oh-my-zsh.sh

export PATH=/Users/musyilmaz/go/bin:$PATH

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
